### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by bangnoise** [bangnoise/ofxHapPlayer#13]
With OF 0.9, using QuickTime becomes a pain on Windows. We should use the DirectShow codec instead. Pull requests very welcome if anyone works on this.

**Comment by yeswecan** [comment]
Can you please help me get a grasp on what will it take to make it work on Windows? I'm not familiar with the architecture yet, but I'm considering making it work. Maybe you have any links to help me figure it all out? 

Thank you in advance.

**Comment by bangnoise** [comment]
Either use the [DirectShow codec](http://renderheads.com/product/hap-for-directshow/) and write a DirectShow-based player which requests DXT frames from that codec, or write a DirectShow-based player which receives still-compressed Hap frames and does the second-stage (Snappy) decompression itself to get the DXT frames - that would have the advantage of not requiring users install the codec, and wouldn't be much more work. You could use the [reference Hap implementation](https://github.com/Vidvox/hap/tree/master/source) to do that.

**Comment by tobiasebsen** [comment]
In order to make ofxHapPlayer campatible with 64-bit on Windows and Mac, I would suggest splitting the class into different classes, which all inherit from a common base class. We could have ofxAVFoundationHapPlayer, ofxDirectShowHapPlayer, ofxQuickTimeHapPlayer, etc. and then typedef the right one to ofxHapPlayer in the main include file "ofxHapPlayer.h"

**Comment by bangnoise** [comment]
The libavformat branch now includes support for Windows (and Linux). It's a work in progress, and when complete will be merged to the main branch.
