### ISSUE TITLE
Can't change speed when playing in thread

### ISSUE THREAD

**Issue by microcosm** [bangnoise/ofxHapPlayer#16]
The video just renders as a black box when I play it at altered speed from a thread:

```cpp
class MyThread : public ofThread {
    
    ofxHapPlayer* hapPlayer;
public:
    void assign(ofxHapPlayer* p){
        hapPlayer = p;
    }
    
    void threadedFunction() {
        hapPlayer->setSpeed(ofRandom(0.2, 4.5));
        hapPlayer->setPosition(0);
        hapPlayer->play();
    }
};

MyThread myThread;

void ofApp::setup(){
    hapPlayer.load("test/video.mov");
    hapPlayer.setLoopState(OF_LOOP_NONE);
    myThread.assign(&hapPlayer);
}

void ofApp::update(){
    hapPlayer.update();
}

void ofApp::draw(){
    hapPlayer.draw(5, 5);
}

void ofApp::keyReleased(int key){
    myThread.startThread(true, false);
}
```

**Comment by bangnoise** [comment]
OF version and platform?

**Comment by microcosm** [comment]
0.9.2 in OSX

**Comment by bangnoise** [comment]
and works otherwise? ie you are on a 32-bit build?

**Comment by bangnoise** [comment]
I'd try constructing the player on the thread - but ofxHapPlayer isn't thread-safe, you would have to lock around calls to it if you want to use it from both threads.

**Comment by microcosm** [comment]
Yes it works fine without the thread. 32 bit build.

I tried constructing the player in the thread and just omitting it entirely
from ofApp class, it gave me the same result, black screen.

I also tried running ofVideoPlayer in the thread instead of ofxHapPlayer.
That works fine. Perhaps it's something to do with the way video is drawn?

**Comment by bangnoise** [comment]
In the interest of getting something workin for you - are you sure the threaded player is necessary? The point of Hap is that it's light on CPU usage.

**Comment by microcosm** [comment]
Thanks. The reason I'm using threads is because I want to delay playback for a precise number of milliseconds. The larger goal is to have several machines on a network play back sound and video clips in sync with each other. So I'm mixing ofxHapPlayer with [ofxNetworkSync](https://github.com/anagma/ofxNetworkSync).

**Comment by bangnoise** [comment]
I don't have time to look into this soon. QuickTime does not like any work happening across threads, so you will have to create the ofxHapPlayer (using ````new ofxHapPlayer()```` and call all its methods on the thread. That will be complicated because ````getTexture()```` will do work in OpenGL which you will have to coordinate with the main thread - and then use that texture on the main thread.

I'm still not convinced this isn't overkill. On a reliable network I've had success using OSC to push frame numbers - see https://github.com/joanielemercier/MediaPlayer_server and https://github.com/joanielemercier/MediaPlayer_client - largely undocumented and for OF 0.8, but worked well.

**Comment by microcosm** [comment]
OK - I will see if ofVideoPlayer can't meet my needs, then branch out from there if needs be.

Thanks for taking the time, much appreciated!
