### ISSUE TITLE
Not Compiling in Windowds 10

### ISSUE THREAD

**Issue by dmelladom** [bangnoise/ofxHapPlayer#25]
Hi, I am trying to compile an example in Windows 10, Visual Studio 2015.
Made a new projec with Project generator and added the add on. Copied src and bin folders into my new Project. I am compiling first 32 bits
There were a lot of errors on the source cpp files. Has anybody tried to compile it in this platform?
Thanks!
D!

**Comment by bangnoise** [comment]
The OpenFrameworks-0.8 branch works with OF 0.8.x on Windows (with Visual Studio 2012).
The OpenFrameworks-0.9 branch doesn't work on Windows due to issues with the ancient QuickTime SDK and VS 2015.
The libavformat branch will work on Windows when it is finished, but doesn't yet - I haven't started work on Windows support.

**Comment by bangnoise** [comment]
The libavformat branch now works on Windows. It's a work in progress and there are some remaining issues, mostly around audio playback. If you try it and hit any problems then reopen this issue (or a new one).
